[package]
name = "canoon"
version = "0.1.0"
edition = "2021"
authors = ["Tim Teichmann"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home = "0.5.9"
git2 = "0.18.3"
